### ISSUE TITLE
Multiple servers with same coin

### ISSUE THREAD

**Issue by xpctxmin** [dvandal/cryptonote-nodejs-pool#189]
Hello,

I want to ask if it is possible in some way or if someone thinks how it could be done, to configure a system with multiple servers located in different places. 
All servers configured with the same currency. 
These servers are accessible with a single url, but that the worker really connects to the server with less hashrate of the moment. 
That is, a system to spread the hashrate between several servers.

Thanks.

**Comment by mtl1979** [comment]
Basically you would need custom DNS server that periodically fetch hash rates from all pools and returns the IP address of the pool with lowest hash rate. It would be easier to just let regular DNS server randomly pick one IP address associated with hostname and rely on worker count instead of hash rates.

**Comment by muscleman** [comment]
GeoDNS
