### ISSUE TITLE
No pool ETN support anymore

### ISSUE THREAD

**Issue by Cideg** [dvandal/cryptonote-nodejs-pool#196]
Hello, unfortunately the new version 1.3.5 unfortunately does not support ETN anymore.
Bad and wrong shares are displayed. Please fix this again.

**Comment by Prog-Maker** [comment]
Superior pool similar - all shares rejected.

**Comment by mannie65** [comment]
Guys i'm running 1.3.5 ETN pool with no issues and have also popped a Block with no issue post fork so i'm not sure what your issue is

**Comment by Cideg** [comment]
Well, I can only report errors with ETN, other coin like Bloc run error free

**Comment by mannie65** [comment]
The only errors i get is from miners that are using non Cryv7 software, or ones that have not set their coin variant correctly. 

There is a bug with Claymore-XMR , but this is not due to the pool software, this is an issue on the ETN side post V6 fork - I have already logged an issue about this with ETN devs on their github page, but there is a workaround
