### ISSUE TITLE
[charts] Unable to get API data for workers_hashrate: SyntaxError: Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by oxzhor** [dvandal/cryptonote-nodejs-pool#393]
Hi peepz,

I have the follow error:

[charts] Unable to get API data for workers_hashrate: SyntaxError: Unexpected token I in JSON at position 0

If i look at my /#worker_stats page then the hashing stats not displayed. The rest works fine.

**Comment by muscleman** [comment]
this is caused by the pool.js making a call to the backend api.js and not having a matching remoteaddress or bindip.
depends on your setup. if you run modules on different boxes. make sure you change set the api.bindIp correctly in config.json. 

in api.js

function authorize attempts to determine if the request was external or internal. note the line 1395. Internally no password is set and the remoteAddress must match.

**Comment by trasherdk** [comment]
I'm seeing the same problem: `Unable to get API data for workers_hashrate`

As far as I can see, the `api.js` function `authorize(request, response)` is not involved in `workers_hashrate` request. It is used in `admin.html` login. 

I do see error on the admin page.

![image](https://user-images.githubusercontent.com/5003891/49847554-55a47b80-fe03-11e8-91ef-dfca24932ecd.png)

**Comment by trasherdk** [comment]
Okay. Got it. I was wrong.

The `api.js` function `authorize(request, response)` is called, at some point, when getting `miners_hashrate` and `workers_hashrate`. Unless you are on the same IP address, the `authorize` will fail, because no password is sent with the request.

A fix could be to present a password, and I took a shortcut:
In `charts.js` function `getUsersHashrates` and `getWorkersHashrates` add password to URI.

`apiInterfaces.pool('/workers_hashrate?password=' + config.api.password , function(error, data)`

**Comment by trasherdk** [comment]
Regarding the admin.html error, the fix was to start wallet-rpc with the `--disable-rpc-login` option,
as no username/password is presented in calls to the rcp daemon..

**Comment by muscleman** [comment]
okay, new pull request was accepted to include sending password to daemon. which works for some daemons
