### ISSUE TITLE
How to reset good blocks marked as orphan?

### ISSUE THREAD

**Issue by SomeFixItDude** [dvandal/cryptonote-nodejs-pool#469]
Hi I had an issue where the unlocker was marking blocks as orphan. Now I would like to go back and have them all re-confirm. How can I reset them?

Is there small nodejs program that I could pass coin and block height... or pass coin and it just iterates over the orphans?

Thanks

**Comment by SomeFixItDude** [comment]
so I attempted on my own...  I did this in redis-cli

ZREM ple:blocks:matured "fdbc83f6a389230dde463569d65bc3c0695baae5365cdd0046482303c4eb0f9b:1556620227:275110804:3184350701:1"
ZADD ple:blocks:candidates 195857 "fdbc83f6a389230dde463569d65bc3c0695baae5365cdd0046482303c4eb0f9b:1556620227:275110804:3184350701:3184350701"

though in the output I on the unlocker I get..

[unlocker] Unlocked 195857 block with reward 465948410772 and donation fee 0. Miners reward: 465948410772
2019-04-30 10:19:11 [unlocker] Unlocked 1 blocks and update balances for 0 workers

How do I get it to update the workers balances?

**Comment by muscleman** [comment]
Zrange coin:blocks:matured 0 -1 withscores

Should help I'd blocks.

Then you need to write a script to read each entry and split on colon. Reassemble with 0 for orphaned instead of 1. Then zdel original and zadd new record

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muscleman** [comment]
not a pool issue, ask in the telegram channel
