### ISSUE TITLE
blocks info broken

### ISSUE THREAD

**Issue by datptolemei** [dvandal/cryptonote-nodejs-pool#529]
Just tested pool on monero testnet, all working good but information about blocks broken. How can I fix that?

![Screenshot_1](https://user-images.githubusercontent.com/58097512/69490945-47763080-0e97-11ea-87f2-dff3b9931f6b.png)

**Comment by muscleman** [comment]
did you fix this?

**Comment by datptolemei** [comment]
still no

**Comment by croniccorey** [comment]
I cannot reproduce this issue on my pools @ https://funwithcrypto.tk

**Comment by muscleman** [comment]
it's because the definition of how a block is stored in redis has changed. block definition now contains 2 additional field prepended to the front. 
[0] rewardType = "prop" or "solo"
[1] minerAddress = substring for security reasons of the miner who found the block.

the front end has code that makes this functionality backward compatiable. see link.

https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/website_example/js/common.js#L536
