### ISSUE TITLE
What do you mean by "Hacked by muscleman" where?

### ISSUE THREAD

**Issue by ilie1988** [dvandal/cryptonote-nodejs-pool#574]
What do you mean by "Hacked by muscleman" where is the hack?

**Comment by dvandal** [comment]
Muscleman wiped the original repo and I needed to recover the files...

**Comment by duyk16** [comment]
Why he can delete your project??

**Comment by mtl1979** [comment]
@dvandal You should have tried to restore the commit history from local copy or one of the forks instead of rebuilding on top of the hacked commit... This way all the diffs from forks would work correctly and making pull requests would also work without rebasing all the cloned repositories/forks on top of the bad commit.

**Comment by trasherdk** [comment]
It's easy. Compare your local copy of the repository, to upstream repository.
@dvandal  rock on. I'll keep an eye on you.

**Comment by muscleman** [comment]
@dvandal asked me to maintain this. Today's code resembles very little of the existing code base. Dynamic frontend, super efficient block retrieval. Anyways was fun. Later

**Comment by muscleman** [comment]
One other thing. I apologize for getting so mad an deleting repo. Just enough is enough. I moved on.
