### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by PsychoSterope** [dvandal/cryptonote-nodejs-pool#78]
It's true, I am still very new to running a pool, but I am at a loss as to how to get mailgun and telegram to work. I have inserted, what I think, are the required things into the config.js but I don't see any output.

Can someone talk me thru the proper setup for these functions?

Thanks!

**Comment by dvandal** [comment]
Take a look at logs/email_error.log and logs/telegram_error.log for any errors.

**Comment by PsychoSterope** [comment]
I don't have those logs... I must be doing something wrong because the the rate charts won't update either. I am going to make a 100% fresh VM and start from scratch and see if I get new results. I am thinking something got screwed up between the rapid fork updates and the pool updates.

**Comment by Talustus** [comment]
regarding telegram(BOT) notifications to a telegram group.
 looks like the API has changed when they added Supergroups and a normal Group can not be reached via @GroupName anymore the prefix for a normal group is most likely "-" now and instead of groupName u have to put the unique ID of the group e.g. 295066805 so it would be "-295066805" 

to allow the telegram bot to accept "-" prefixed values a quick change i have applyed to the code is:

`diff --git a/lib/notifications.js b/lib/notifications.js
index 117a2f4..89fb30f 100644
--- a/lib/notifications.js
+++ b/lib/notifications.js
@@ -86,8 +86,7 @@ exports.sendToAll = function(id, variables) {
             return ;
         }

-        var chatId = '@' + channel;
-        telegram.sendMessage(chatId, message);
+        telegram.sendMessage(channel, message);
     }

     // Send email
@@ -167,8 +166,7 @@ exports.sendToTelegramChannel = function(id, variables) {
             return ;
         }

-        var chatId = '@' + channel;
-        telegram.sendMessage(chatId, message);
+        telegram.sendMessage(channel, message);
     }
 }

diff --git a/lib/telegramBot.js b/lib/telegramBot.js
index ac0a673..c92ce6c 100644
--- a/lib/telegramBot.js
+++ b/lib/telegramBot.js
@@ -68,8 +68,8 @@ var bot = new TelegramBot(token, {polling: true});
  **/

 if (periodicalStats && statsInterval > 0 && channel) {
-    log('info', logSystem, 'Sending pool statistics to telegram channel @%s each %d minutes', [channel, statsInterval]);
-    setInterval(function(){ sendPoolStats('@'+channel); }, (statsInterval*60)*1000);
+    log('info', logSystem, 'Sending pool statistics to telegram channel %s each %d minutes', [channel, statsInterval]);
+    setInterval(function(){ sendPoolStats(channel); }, (statsInterval*60)*1000);
 }

 /**
`
This is maybe a quick and dirty FIX

@dvandal may should check and maybe add code to accept @ or -

**Comment by PsychoSterope** [comment]
I think I have Telegram working. But I am nto sure about mailgun. Under mail gun I have "key": "key-xxxxxxxx" with the domian.. Do I need to enable email or are there any other settings in the pool I need to change to make mailgun work?

**Comment by PsychoSterope** [comment]
Problems all solved! I didn't realize I need to change "transport": "sendmail" to "transport": "mailgun"
